# Site settings
title: "Rapport Tecnológia"
email: "admin@rapport.tec.br"

tags: []
description: "Rappot Tecnológia é uma empreendimento fortemente atrelado a intelgiência Artificial, visamos oferecer serviços classicos empoderados tanto por Recursos Humanos como Inteligência Artificial. Temos mais de 35 anos de experiência em integração de sistemas, redes e desenvolvimento de softwares. Da Hospedagem do seu site, até a integração de seus sistemas com meios de comunicação via internet, buscamos a melhor solução."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: ""
github_username: rapporttecnologia

# Build settings
markdown: kramdown

collections:  
  pages:
    output: true
    permalink: /:path/